version: 0.2
env:
  variables:
    S3_BUCKET: "shuheiktgw-movies"
    PACKAGES: "github.com/shuheiktgw/lambda-codepipeline"

phases:
  install:
    commands:
      - mkdir -p "/go/src/$(dirname ${PACKAGES})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGES}"
      - go get -u github.com/golang/lint/golint
      - go get -u github.com/golang/dep/cmd/dep

  pre_build:
    commnds:
      - cd "/go/src/${PACKAGES}"
      - dep ensure
      - golint -set_exit_status
      - go vet .
      - go test .

  build:
    commands:
      - dep ensure
      - GOOS=linux go build -o main
      - zip $CODEBUILD_RESOLVED_SOURCE_VERSION.zip main
      - aws s3 cp $CODEBUILD_RESOLVED_SOURCE_VERSION.zip s3://$S3_BUCKET/

  post_build:
    commands:
      - aws lambda update-function-code --function-name FindAllMovies --s3-bucket $S3_BUCKET --s3-key $CODEBUILD_RESOLVED_SOURCE_VERSION.zip